server: server_connection.cpp server_main.cpp socket_util.cpp server_databuffer.cpp server_result.cpp
	g++ -std=gnu++11 -g -pthread -o server_run server_result.cpp server_databuffer.cpp server_connection.cpp server_main.cpp socket_util.cpp -I.
